App_Cart/urls.py
from django.urls import path

app_name='App_Cart'

urlpatterns = [
 
]

App_Products/urls.py
from django.urls import path
from App_Products import views

app_name='App_Products'

urlpatterns = [
    #path('all_products/',views.all_products,name='all_products'),

    path('category/<str:category_name>/', views.category_products, name='category_products'),
    path('category/<str:category_name>/<str:subcategory_name>/', views.category_products, name='subcategory_products'),
    path('single_product/<int:pk>/',views.single_product,name='single_product'),
    path('shop_products/',views.shop_products,name='shop_products'),
    path('search_by_category/',views.search_by_category,name='search_by_category'),
    path('product_search/',views.product_search,name='product_search'),
    path('search_by_price/',views.search_by_price,name='search_by_price'),
    path('filter_by_category/<str:category_name>/', views.filter_by_category, name='filter_by_category'),


]

ShopOnline/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App_Home.urls')),
    path('accounts/',include('App_Accounts.urls')),
    path('cart/',include('App_Cart.urls')),
    path('order/',include('App_Order.urls')),
    path('payment/',include('App_Payment.urls')),
    path('products/',include('App_Products.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Products/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Categories"



class Sub_Category(models.Model):
    title = models.CharField(max_length=20)
    categorys = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='categorys')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Sub_Categories"



class Color(models.Model):
    name=models.CharField(max_length=30)
    #color_code=models.CharField(max_length=50, null=True,blank=True)

    def __str__(self):
        return self.name



class Size(models.Model):
    name=models.CharField(max_length=30)

    def __str__(self):
        return self.name
   


class Product(models.Model):
    mainimage = models.ImageField(upload_to='Products')
    name = models.CharField(max_length=264)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    sub_category = models.ForeignKey(Sub_Category, on_delete=models.CASCADE, null=True,blank=True, related_name='sub_category')
    preview_text = models.TextField(max_length=400, verbose_name='Preview Text')
    detail_text = models.TextField(max_length=1000, verbose_name='Description')
    additional_info=models.TextField(max_length=1000, verbose_name='Additional Info')
    sku=models.CharField(max_length=30)
    price = models.FloatField()
    old_price = models.FloatField(default=0.00)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created',]

class Product_Color(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE,related_name='color_variants')
    color = models.ForeignKey(Color, on_delete=models.CASCADE,related_name='product_color')

    def __str__(self):
        return f"{self.product.name} - {self.color.name}"
    
class Product_Size(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='size_variants')
    size = models.ForeignKey(Size, on_delete=models.CASCADE,related_name='product_size')

    def __str__(self):
        return f"{self.product.name} - {self.size.name}"
    
class Product_Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='image_variants')
    image = models.ImageField(upload_to='Products')

    def __str__(self):
        return f"{self.product.name}"
    

App_Products/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect,get_object_or_404,Http404
from django.views.generic import ListView, DetailView

from App_Products.models import Product,Product_Size,Category,Sub_Category,Size,Color
from App_Order.models import Cart
from django.db.models import Count
from django.contrib.auth.mixins import LoginRequiredMixin



def all_products(request):

        products = Product.objects.all()
        product_details = []

        for product in products:
            size_variants = product.size_variants.all()
            color_variants = product.color_variants.all()
            product_detail = {
                'products':products,
                'name': product.name,
                'sku':product.sku,
                'price':product.price,
                'old_price':product.old_price,
                'mainimage':product.mainimage,

                'category':product.category.title,

                'sizes': [size_variant.size.name for size_variant in size_variants],
                'colors':[color_variant.color.name for color_variant in color_variants]
            }

            product_details.append(product_detail)
        combined_data = [{'object': obj, 'product_name': name} for obj, name in zip(products, product_details)]

        context = {'combined_data': combined_data}

        return render(request, 'App_Products/Category/all_products.html', context)



def category_products(request, category_name, subcategory_name=None):
    category = get_object_or_404(Category, title=category_name)

    selected_subcategory = None
    subcategory_products = []

    if subcategory_name:
        selected_subcategory = get_object_or_404(Sub_Category, title=subcategory_name, categorys=category)
        subcategory_products = selected_subcategory.sub_category.all()

    products = Product.objects.filter(category=category)
    subcategories = Sub_Category.objects.filter(categorys=category)

    context = {
         
        'category': category,
        'products': subcategory_products if subcategory_name else products,
        'subcategories': subcategories if not subcategory_name else [],
        'selected_subcategory': selected_subcategory,
        'subcategory_products': subcategory_products,
        'subcategory':subcategory_name
    }

    return render(request, 'App_Products/Sub_Category/category_products.html', context)

def single_product(request, pk):
    
    product = Product.objects.get(id=pk)
    
    size_variants = product.size_variants.all()
    color_variants = product.color_variants.all()

    context = {
        'product_id':product.id,
        'name': product.name,
        'price': product.price,
        'old_price': product.old_price,
        'preview': product.preview_text,
        'description': product.detail_text,
        'additional_info': product.additional_info,
        'sizes': [size_variant.size.name for size_variant in size_variants],
        'colors': [color_variant.color.name for color_variant in color_variants],
        'sku': product.sku,
        'category': product.category.title,
        'mainimage': product.mainimage,
   
    }

    return render(request, 'App_Products/single_product.html', context)

def shop_products(request):
        
    products = Product.objects.all()
    num_of_products=products.count()

    #To see last 3 products
    new_added=products.order_by('-id')[:3]
    product_details = []

    for product in products:
        size_variants = product.size_variants.all()
        color_variants = product.color_variants.all()
        product_detail = {
            'products':products,
            'name': product.name,
            'sku':product.sku,
            'price':product.price,
            'old_price':product.old_price,
            'mainimage':product.mainimage,
            'category':product.category.title,
            'sizes': [size_variant.size.name for size_variant in size_variants],
            'colors':[color_variant.color.name for color_variant in color_variants]
        }

        product_details.append(product_detail)
    combined_data = [{'object': obj, 'product_name': name} for obj, name in zip(products, product_details)]

    context = {'combined_data': combined_data,'new_added':new_added,'num_of_products':num_of_products}

    return render(request, 'App_Products/shop_products.html', context)

def search_by_price(request):
    if request.method=='POST':
        products=Product.objects.all()
        min_price=request.POST.get('min')
        max_price=request.POST.get('max')
        product_details = []
        num_of_products=0

        products_in_range = Product.objects.filter(price__range=(min_price, max_price))
        num_of_products=products_in_range.count()
        for product in products_in_range:
                size_variants = product.size_variants.all()
                color_variants = product.color_variants.all()

                product_detail = {
                    'products':products,
                    'name': product.name,
                    'sku':product.sku,
                    'price':product.price,
                    'old_price':product.old_price,
                    'mainimage':product.mainimage,
                    'category':product.category.title,
                    'sizes': [size_variant.size.name for size_variant in size_variants],
                    'colors':[color_variant.color.name for color_variant in color_variants]
                }
                product_details.append(product_detail)
                
                
        combined_data = [{'object': obj, 'product_name': name} for obj, name in zip(products, product_details)]

    context = {'combined_data': combined_data,'num_of_products':num_of_products}
          
    return render(request, 'App_Products/shop_products.html', context)
    
    

def search_by_category(request):
    if request.method=='POST':
        products=Product.objects.all()
        product_details = []
        num_of_products=products.count()
        for product in products:
            product_details.append(product)

        category_name=request.POST.get('service')
        search=request.POST.get('search')
        
        
        if category_name:
            category=Category.objects.get(title=category_name)
            category_id = category.id
            products=Product.objects.filter(category=category_id,name__icontains=search)
            num_of_products=products.count()

            
            for product in products:
                size_variants = product.size_variants.all()
                color_variants = product.color_variants.all()
                product_detail = {
                    'products':products,
                    'name': product.name,
                    'sku':product.sku,
                    'price':product.price,
                    'old_price':product.old_price,
                    'mainimage':product.mainimage,
                    'category':product.category.title,
                    'sizes': [size_variant.size.name for size_variant in size_variants],
                    'colors':[color_variant.color.name for color_variant in color_variants]
                }
                product_details.append(product_detail)
                
                
        combined_data = [{'object': obj, 'product_name': name} for obj, name in zip(products, product_details)]

    context = {'combined_data': combined_data,'num_of_products':num_of_products}
          
    return render(request, 'App_Products/shop_products.html', context)


def filter_by_category(request,category_name):
    category=Category.objects.get(title=category_name)
    category_id=category.id
    products=Product.objects.filter(category=category_id)
    num_of_products=products.count()
    product_details = []
    if products:
        for product in products:
                size_variants = product.size_variants.all()
                color_variants = product.color_variants.all()
                product_detail = {
                    'products':products,
                    'name': product.name,
                    'sku':product.sku,
                    'price':product.price,
                    'old_price':product.old_price,
                    'mainimage':product.mainimage,
                    'category':product.category.title,
                    'sizes': [size_variant.size.name for size_variant in size_variants],
                    'colors':[color_variant.color.name for color_variant in color_variants]
                }
                product_details.append(product_detail)
                
                
        combined_data = [{'object': obj, 'product_name': name} for obj, name in zip(products, product_details)]

    context = {'combined_data': combined_data,'num_of_products':num_of_products}
          
    return render(request, 'App_Products/shop_products.html', context)
    

def filter_by_size(request,size_name):
    #size_counts = Size.objects.annotate(product_count=Count('product_size'))
    
    size = Size.objects.get(name=size_name)
    products = Product_Size.objects.filter(size=size)


    num_of_products=products.count()
    product_details = []
    if products:
        for product in products:
                size_variants = product.size_variants.all()
                color_variants = product.color_variants.all()
                product_detail = {
                    'products':products,
                    'name': product.name,
                    'sku':product.sku,
                    'price':product.price,
                    'old_price':product.old_price,
                    'mainimage':product.mainimage,
                    'category':product.category.title,
                    'sizes': [size_variant.size.name for size_variant in size_variants],
                    'colors':[color_variant.color.name for color_variant in color_variants]
                }
                product_details.append(product_detail)
                

templates/App_Products/shop_products.html
{% extends 'base.html'%}
{% load static %}
{% load cart_tags %}
{% block title_block %} ShopOnline {% endblock %}
{% block body_block %}
<div class="shop-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="shop-filter-wrap">
                    <div class="filter-item">
                        <div class="shop-filter-item">
                            <div class="shop-filter-search">
                                <form method="GET" action="{% url 'App_Products:product_search' %}">
                                    <div>
                                        <input type="text" class="form-control" placeholder="Search.." name="src">
                                        <button type="submit"><i class="ti-search"></i></button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="filter-item">
                        <div class="shop-filter-item category-widget">
                            <h2>Categories</h2>
                            <ul>
                                {% for category in categories%}
                                <li><a href="{% url 'App_Products:filter_by_category' category_name=category.title %}">{{category.title}}<span>
                                            ({{ category | get_product_count }}) </span></a></li>
                                {%endfor%}
                            </ul>
                        </div>
                    </div>
                    <div class="filter-item">
                        <div class="shop-filter-item">
                            <h2>Filter by price</h2>
                            <div class="shopWidgetWraper">
                                <div class="priceFilterSlider">
                                    <!--
                                    <form action="#" method="get" class="clearfix">
                                        -->
                                    <form method="POST" action="{% url 'App_Products:search_by_price' %}"
                                        class="clearfix">
                                        {% csrf_token %}

                                        <!-- <div id="sliderRange"></div>
                                        <div class="pfsWrap">
                                            <label>Price:</label>
                                            <span id="amount"></span>
                                        </div> -->
                                        <div class="d-flex">
                                            <div class="col-lg-6 pe-2">
                                                <label for="" class="form-label">Min</label>
                                                <input type="text" class="form-control" placeholder="Min" value="0"
                                                    name="min">
                                            </div>
                                            <div class="col-lg-6">
                                                <label for="" class="form-label">Max</label>
                                                <input type="text" class="form-control" placeholder="Max" value="100000"
                                                    name="max">
                                            </div>
                                        </div>
                                        <div class="col-lg-12 mt-4">
                                            <button class="form-control bg-light">Search</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="filter-item">
                        <div class="shop-filter-item">
                            <h2>Color</h2>
                            <ul>
                                {% for color in all_colors%}
                                <li>
                                    <label class="topcoat-radio-button__label">{{color}}<span>({{ color | product_count_by_color }})</span>
                                        <input type="radio" name="topcoat2">
                                        <span class="topcoat-radio-button"></span>
                                    </label>
                                </li>
                                {% endfor %}

                            </ul>
                        </div>
                    </div>
                    <div class="filter-item">
                        <div class="shop-filter-item">
                            <h2>Size</h2>
                            <ul>
                                {% for size in all_sizes%}
                                <li>
                                    <label class="topcoat-radio-button__label">{{size}}<span>({{ size | product_count_by_size }})</span>
                                        <input type="radio" name="topcoat3">
                                        <span class="topcoat-radio-button"></span>
                                    </label>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="filter-item">
                        <div class="shop-filter-item new-product">
                            <h2>New Products</h2>
                            <ul>
                                {% for data in new_added %}
                                <li>
                                    <div class="product-card">
                                        <div class="card-image">
                                            <div class="image">
                                                <img src="{{data.mainimage.url}}" alt="">
                                            </div>
                                        </div>
                                        <div class="content">
                                            <h3><a
                                                    href="{% url 'App_Products:single_product' pk=data.id %}">{{data.name}}</a>
                                            </h3>
                                            <div class="rating-product">
                                                <i class="fi flaticon-star"></i>
                                                <i class="fi flaticon-star"></i>
                                                <i class="fi flaticon-star"></i>
                                                <i class="fi flaticon-star"></i>
                                                <i class="fi flaticon-star"></i>
                                                <span>30</span>
                                            </div>
                                            <div class="price">
                                                <span class="present-price">&#2547; {{data.price|floatformat:2}}</span>
                                                <del class="old-price">&#2547; {{data.old_price|floatformat:2}}</del>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="filter-item">
                        <div class="shop-filter-item tag-widget">
                            <h2>Popular Tags</h2>
                            <ul>
                                <li><a href="#">Fashion</a></li>
                                <li><a href="#">Shoes</a></li>
                                <li><a href="#">Kids</a></li>
                                <li><a href="#">Theme</a></li>
                                <li><a href="#">Stylish</a></li>
                                <li><a href="#">Women</a></li>
                                <li><a href="#">Shop</a></li>
                                <li><a href="#">Men</a></li>
                                <li><a href="#">Blog</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="shop-section-top-inner">
                    <div class="shoping-product">
                        <p>We found <span>{{num_of_products}} items </span> for you!</p>
                    </div>
                    <div class="short-by">
                        <ul>
                            <li>
                                Sort by:
                            </li>
                            <li>
                                <select name="show">
                                    <option value="">Default Sorting</option>
                                    <option value="">Low To High</option>
                                    <option value="">High To Low</option>
                                </select>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="product-wrap">
                    <div class="row align-items-center">


                        {% for data in combined_data %}

                        <div class="col-lg-4 col-md-4 col-sm-6 col-12">
                            <div class="product-item">
                                <div class="image">
                                    <img src="{{data.product_name.mainimage.url}}" style="width:100%; height:300px;">
                                    <div class="tag new">New</div>
                                </div>
                                <div class="text">
                                    <h2><a href="{% url 'App_Products:single_product' pk=data.object.id %}">{{data.product_name.name}}</a></h2>
                                    <div class="rating-product">
                                        <i class="fi flaticon-star"></i>
                                        <i class="fi flaticon-star"></i>
                                        <i class="fi flaticon-star"></i>
                                        <i class="fi flaticon-star"></i>
                                        <i class="fi flaticon-star"></i>
                                        <span>130</span>
                                    </div>
                                    <div class="price">
                                        <span class="present-price">&#2547;{{data.product_name.price|floatformat:2}}</span>
                                        <del class="old-price">&#2547;{{data.product_name.old_price|floatformat:2}}</del>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}