App_Accounts/urls.py
from django.urls import path
from App_Accounts import views


app_name='App_Accounts'

urlpatterns = [
    path('login/',views.login_user, name='login'),
    path('logout/',views.logout_user,name='logout'),
    path('register/',views.register, name='register'),
    path('success/',views.success, name='success'),
    #path('verify/<str:auth_token>/',views.verify_account, name='verify_account'),
    path('verify/',views.verify_account, name='verify_account'),
    path('customer_details/<int:pk>/',views.customerDetails,name='customer_details'),
    path('forgot/',views.forgot_pass, name='forgot'),
    path('reset_verify/<str:auth_token>/',views.reset_verify, name='reset_verify'),
    path('profile_update/',views.profile_update,name='profile_update'),
    
]

App_Cart/urls.py
from django.urls import path

app_name='App_Cart'

urlpatterns = [
 
]

App_Home/urls.py
from django.urls import path
from App_Home import views



app_name='App_Home'

urlpatterns = [
    path('',views.home ,name='home'),
    path('contact/',views.contact ,name='contact'),
]

ShopOnline/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App_Home.urls')),
    path('accounts/',include('App_Accounts.urls')),
    path('cart/',include('App_Cart.urls')),
    path('order/',include('App_Order.urls')),
    path('payment/',include('App_Payment.urls')),
    path('products/',include('App_Products.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="wpOceans">
    <link rel="shortcut icon" type="image/png" href="{% static 'assets/images/favicon.png' %}">
    <title> {% block title_block %} ShopOnline {% endblock %}</title>
    <link href="{% static 'assets/css/themify-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/flaticon_ecommerce.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/owl.carousel.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/owl.theme.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/slick.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/slick-theme.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/swiper.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/owl.transitions.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/jquery.fancybox.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/odometer-theme-default.css' %}" rel="stylesheet">
    <link href="{% static 'assets/sass/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
</head>

<body>

    <!-- start page-wrapper -->
    <div class="page-wrapper">
        <!-- start preloader -->
        <div class="preloader">
            <div class="vertical-centered-box">
                <div class="content">
                    <div class="loader-circle"></div>
                    <div class="loader-line-mask">
                        <div class="loader-line"></div>
                    </div>
                    <img src="{% static 'assets/images/preloader.png' %}" alt="">
                </div>
            </div>
        </div>
        <!-- end preloader -->

{% include 'header.html' %}

<div class="container">
  <div class="messages container mt-2">
    {% if messages %}
      {% for message in messages %}
        <div {% if message.tags %} class="alert alert-{{message.tags}}{% endif %}" role="alert">
          {{message}}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
      {% endfor %}
    {% endif %}
  </div>
    {% block body_block %} 
    <h1>This is from body block</h1>
  
    {% endblock %}

  </div>
{% include 'footer.html' %}
    </div>
    <!-- end of page-wrapper -->

    <!-- All JavaScript files
    ================================================== -->
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Plugins for this template -->
    <script src="{% static 'assets/js/modernizr.custom.js' %}"></script>
    <script src="{% static 'assets/js/jquery.dlmenu.js' %}"></script>
    <script src="{% static 'assets/js/jquery-plugin-collection.js' %}"></script>
    <!-- Custom script for this template -->
    <script src="{% static 'assets/js/script.js' %}"></script>
</body>
</html>

templates/base2.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="wpOceans">
    <link rel="shortcut icon" type="image/png" href="{% static 'assets/images/favicon.png'%}">
    <title> {% block title_block %} ShopOnline {% endblock %}</title>
    <link href="{% static 'assets/css/themify-icons.css'%}" rel="stylesheet">
    <link href="{% static 'assets/css/font-awesome.min.css'%}" rel="stylesheet">
    <link href="{% static 'assets/css/flaticon_ecommerce.css'%}" rel="stylesheet">
    <link href="{% static 'assets/css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'assets/css/animate.css'%}" rel="stylesheet">
    <link href="{% static 'assets/css/owl.carousel.css'%}" rel="stylesheet">
    <link href="{% static 'assets/css/owl.theme.css'%}" rel="stylesheet">
    <link href="{% static 'assets/css/slick.css'%}" rel="stylesheet">
    <link href="{% static 'assets/css/slick-theme.css'%}" rel="stylesheet">
    <link href="{% static 'assets/css/swiper.min.css'%}" rel="stylesheet">
    <link href="{% static 'assets/css/owl.transitions.css'%}" rel="stylesheet">
    <link href="{% static 'assets/css/jquery.fancybox.css'%}" rel="stylesheet">
    <link href="{% static 'assets/css/odometer-theme-default.css'%}" rel="stylesheet">
    <link href="{% static 'assets/sass/style.css'%}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
    <link href="{% static 'assets/css/profile.css'%}" rel="stylesheet">
    <link href="{% static 'assets/css/profile_update.css'%}" rel="stylesheet">


</head>

<body>

    <!-- start page-wrapper -->
    <div class="page-wrapper">
        <!-- start preloader -->
        <div class="preloader">
            <div class="vertical-centered-box">
                <div class="content">
                    <div class="loader-circle"></div>
                    <div class="loader-line-mask">
                        <div class="loader-line"></div>
                    </div>
                    <img src="{% static 'assets/images/preloader.png'%}" alt="">
                </div>
            </div>
        </div>
        <!-- end preloader -->

{% include 'header2.html' %}
<div class="container">
    <div class="messages container mt-2">
      {% if messages %}
        {% for message in messages %}
          <div {% if message.tags %} class="alert alert-{{message.tags}}{% endif %}" role="alert">
            {{message}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          </div>
        {% endfor %}
      {% endif %}
    </div>
    {% block body_block %} 
    <h1>This is from body block</h1>
  
    {% endblock %}

  </div>
    </div>
    <!-- end of page-wrapper -->

    <!-- All JavaScript files
    ================================================== -->
    <script src="{% static 'assets/js/jquery.min.js'%}"></script>
    <script src="{% static 'assets/js/bootstrap.bundle.min.js'%}"></script>
    <!-- Plugins for this template -->
    <script src="{% static 'assets/js/modernizr.custom.js'%}"></script>
    <script src="{% static 'assets/js/jquery.dlmenu.js'%}"></script>
    <script src="{% static 'assets/js/jquery-plugin-collection.js'%}"></script>
    <!-- Custom script for this template -->
    <script src="{% static 'assets/js/script.js'%}"></script>
</body>
</html>

templates/category_products.html
<!-- category_products.html -->

<h2>{{ category.title }} Products</h2>

<ul>
  {% for product in products %}
    <li>{{ product.name }}</li>
  {% endfor %}
</ul>

{% if subcategories %}
  <h3>Subcategories</h3>
  <ul>
    {% for subcategory in subcategories %}
      <li>
          {{ subcategory.title }}
        </a>
      </li>
    {% endfor %}
  </ul>
{% endif %}

{% if selected_subcategory %}
  <h3>{{ selected_subcategory.name }} Products</h3>
  <ul>
    {% for product in subcategory_products %}
      <li>{{ product.name }}</li>
    {% endfor %}
  </ul>
{% endif %}

templates/footer.html
{% load static %}
<footer class="wpo-site-footer">
    <div class="wpo-upper-footer">
        <div class="container">
            <div class="row">
                <div class="col col-lg-3 col-md-6 col-sm-12 col-12">
                    <div class="widget about-widget">
                        <div class="logo widget-title">
                            <img src="{% static 'assets/images/logo-2.svg'%}" alt="blog">
                        </div>
                        <p>Elit commodo nec urna erat morbi at hac turpis aliquam.
                            In tristique elit nibh turpis. Lacus volutpat ipsum convallis tellus pellentesque
                            etiam.</p>
                        <ul>
                            <li>
                                <a href="#">
                                    <i class="ti-facebook"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="ti-twitter-alt"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="ti-linkedin"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="ti-instagram"></i>
                                </a>
                            </li>
                        </ul>

                    </div>
                </div>
                <div class="col col-lg-3 col-md-6 col-sm-12 col-12">
                    <div class="widget link-widget">
                        <div class="widget-title">
                            <h3>Contact Us</h3>
                        </div>
                        <div class="contact-ft">
                            <ul>
                                <li><i class="fi flaticon-mail"></i>themart@gmail.com</li>
                                <li><i class="fi flaticon-phone"></i>(208) 555-0112 <br>(704) 555-0127</li>
                                <li><i class="fi flaticon-pin"></i>4517 Washington Ave. Manchter,
                                    Kentucky 495</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col col-xl-3 col-lg-2 col-md-6 col-sm-12 col-12">
                    <div class="widget link-widget">
                        <div class="widget-title">
                            <h3>Popular</h3>
                        </div>
                        <ul>
                            <li><a href="product.html">Men</a></li>
                            <li><a href="product.html">Women</a></li>
                            <li><a href="product.html">Kids</a></li>
                            <li><a href="product.html">Shoe</a></li>
                            <li><a href="product.html">Jewelry</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col col-xl-3 col-lg-4 col-md-6 col-sm-12 col-12">
                    <div class="widget instagram">
                        <div class="widget-title">
                            <h3>Instagram</h3>
                        </div>
                        <ul class="d-flex">
                            <li><a href="project-single.html"><img src="{% static 'assets/images/instragram/1.jpg'%}"
                                        alt=""></a></li>
                            <li><a href="project-single.html"><img src="{% static 'assets/images/instragram/2.jpg'%}"
                                        alt=""></a></li>
                            <li><a href="project-single.html"><img src="{% static 'assets/images/instragram/4.jpg'%}"
                                        alt=""></a></li>
                            <li><a href="project-single.html"><img src="{% static 'assets/images/instragram/3.jpg'%}"
                                        alt=""></a></li>
                            <li><a href="project-single.html"><img src="{% static 'assets/images/instragram/4.jpg'%}"
                                        alt=""></a></li>
                            <li><a href="project-single.html"><img src="{% static 'assets/images/instragram/1.jpg'%}"
                                        alt=""></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div> <!-- end container -->
    </div>
    <div class="wpo-lower-footer">
        <div class="container">
            <div class="row">
                <div class="col col-xs-12">
                    <p class="copyright"> Copyright &copy; 2023 Themart by <a href="index.html">wpOceans</a>.
                        All
                        Rights Reserved.</p>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/header2.html
{% load static %}
{% load cart_tags %}
<header id="header">
    <!-- end topbar -->
    <!--  start header-middle -->
    <div class="header-middle">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-2">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="{% url 'App_Home:home' %}"><img src="{% static 'assets/images/logo.svg'%}"
                                    alt="logo"></a>
                    </div>
                </div>           
                <div class="col-lg-4 col-12">
                    </div>
                <div class="col-lg-6 col-12 text-right"> <div class="middle-right">
                        <ul>
                            {%if user.is_authenticated%}
                            <li><a href="{% url 'App_Accounts:logout' %}"><i class="fi flaticon-user-profile"></i><span>Logout</span></a></li>
                            {%endif%}                              
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <!--  end header-middle -->
    <div class="wpo-site-header">
        <nav class="navigation navbar navbar-expand-lg navbar-light">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-3 col-md-3 col-sm-3 col-3 d-lg-none dl-block">
                        <div class="mobail-menu">
                            <button type="button" class="navbar-toggler open-btn">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar first-angle"></span>
                                <span class="icon-bar middle-angle"></span>
                                <span class="icon-bar last-angle"></span>
                            </button>
                        </div>
                    </div>
                </div>
            </div><!-- end of container -->
        </nav>
    </div>
</header>